### ISSUE TITLE
Config keys unknown

### ISSUE THREAD

**Issue by michaeltoohig** [mopidy/mopidy-alsamixer#18]
On rpi 3 running mopidy/mopidy-alsamixer as a service and installed via apt.

`min_volume`, `max_volume`, and `volume_scale` are all causing a warning and disabling the extension. If I remove those config keys then mopidy will work but without any volume controls.

Is this the result of some known configuration error or a bug? The rest of my configuration file is default besides the audio.

![image](https://user-images.githubusercontent.com/34083701/59505766-1c53e200-8ef2-11e9-88a7-dea95dfb1c36.png)

**Comment by jodal** [comment]
You are probably running Raspbian based on Debian Stretch (the last stable release). Debian Stretch have Mopidy-AlsaMixer 1.0.3, as you can see from https://packages.debian.org/search?keywords=mopidy-alsamixer or by running `dpkg -l mopidy-alsamixer` on your system.

The configs in question was only added to Mopidy-AlsaMixer 1.1.0, as you can see in [the changelog](https://github.com/mopidy/mopidy-alsamixer#changelog).

The next stable version of Debian, named Buster, includes Mopidy-AlsaMixer 1.1.1. It is due to be released in July, and Raspbian will probably follow up with a new release within a few months after that.

If you don't want to wait for that, you can install newer versions of the Mopidy Debian packages from https://apt.mopidy.com.
